[package]
name = "foo"
version = "0.1.0"
edition = "2021"
rust-version = "1.68.0"

[dependencies]
# FAILS
sysinfo = { version = "0.27", default-features = false }

# BUILDS
#sysinfo = { version = "0.27" }

